<a href="https://colab.research.google.com/github/johncaps2/johncaps2/blob/main/Functions_Warmup_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
from matplotlib import pyplot as plt
import math

def Req_Parallel(R1, R2, R3):
  """Calculate the equivalent resistance of 3 resistors in parallel"""
  Req = 1/(1/R1 + 1/R2 + 1/R3)
  return Req


In [60]:
R1 = 10
R2 = 20
R3 = 50

assert math.isclose(Req_Parallel(R1,R2,R3), 5.882, abs_tol=1.e-3)
print(f"The resistance over the 3 parallel resistors is {Req_Parallel(R1,R2,R3)}")

The resistance over the 3 parallel resistors is 5.88235294117647


In [65]:
def ReqParallel2(rlist):
  """Calculate Req for list of resistors in parallel

  Parameters getting passed in:
  rlist = list of resistors, resistance in Ohms

  RETURN:
  Req = returns the equivalent resistance"""

  req_inv = 0
  for r in rlist:
    req_inv += 1/r
  return 1/req_inv

In [66]:
resistor_list = [10,20,50]
ReqParallel2(resistor_list)

5.88235294117647

# Solving systems of equations

In [67]:
import numpy as np

In [68]:
R1 = 2
R2 = 4
R3 = 4
R4 = 2
V1 = 50
V2 = 20

In [75]:
A = np.array([[R1, R2, 0, 0], [R1, 0, R3, 0], [R1, 0, 0, R4], [1, -1, -1, -1]])

In [76]:
A

array([[ 2,  4,  0,  0],
       [ 2,  0,  4,  0],
       [ 2,  0,  0,  2],
       [ 1, -1, -1, -1]])

In [77]:
B = np.array([V1, V1, V1+V2, 0])

In [78]:
B

array([50, 50, 70,  0])

In [79]:
np.linalg.solve(A,B)

array([20. ,  2.5,  2.5, 15. ])